var langConf = {
    availableLangs_from : "auto,|,ar,bg,zh,hr,cs,da,nl,en,fi,fr,de,el,hi,it,jp,ko,no,po,pt,ro,ru,es,sv",
    availableLangs_to : "ar,bg,zh-CN,zh-TW,hr,cs,da,nl,en,fi,fr,de,el,hi,it,jp,ko,no,po,pt,ro,ru,es,sv",
    langDict : {
        "auto" : "auto",
        "ar" : "arabic",
        "bg" : "bulgarian",
        "zh" : "chinese",
        "zh-CN" : "chineseS",
        "zh-TW" : "chineseT",
        "hr" : "croatian",
        "cs" : "czech",
        "da" : "danish",
        "nl" : "dutch",
        "en" : "english",
        "fi" : "finnish",
        "fr" : "french",
        "de" : "german",
        "el" : "greek",
        "hi" : "hindi",
        "it" : "italian",
        "jp" : "japanese",
        "ko" : "korean",
        "no" : "norwegian",
        "po" : "polish",
        "pt" : "portuguese",
        "ro" : "romanian",
        "ru" : "russian",
        "es" : "spanish",
        "sv" : "swedish"
    }
}